// This file is generated by rust-protobuf 3.3.0. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `CmdId.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_3_0;

#[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
// @@protoc_insertion_point(enum:pbdef.CmdId)
pub enum CmdId {
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_None)
    C_None = 0,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_GM)
    C_GM = 1,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_Online)
    C_Online = 1000,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_UserDataChangeNotify)
    C_UserDataChangeNotify = 100101,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_PlayerLevelUpNotify)
    C_PlayerLevelUpNotify = 100103,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_OtherPlaceLoginKickoutNotify)
    C_OtherPlaceLoginKickoutNotify = 100104,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_ServerWillShutdownNotify)
    C_ServerWillShutdownNotify = 100105,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_ActivityInfoChangeNotify)
    C_ActivityInfoChangeNotify = 100106,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_UserActivityInfoChangeNotify)
    C_UserActivityInfoChangeNotify = 100107,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_BeKickOutNotify)
    C_BeKickOutNotify = 100108,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_UserHeroImageUnlockNotify)
    C_UserHeroImageUnlockNotify = 100109,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_SystemMessageNotify)
    C_SystemMessageNotify = 100110,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_SystemOfflineNotify)
    C_SystemOfflineNotify = 100111,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_ConnectionExpireNotify)
    C_ConnectionExpireNotify = 100112,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_CommonStartNotify)
    C_CommonStartNotify = 100113,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_Login)
    C_Login = 1000001,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_Re_Login)
    C_Re_Login = 1000002,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_FriendsGet)
    C_FriendsGet = 1009000,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_FriendsApply)
    C_FriendsApply = 1009001,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_FriendsDel)
    C_FriendsDel = 1009002,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_FriendsApplyReply)
    C_FriendsApplyReply = 1009003,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_FriendsMoveToBlackList)
    C_FriendsMoveToBlackList = 1009004,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_FriendsSendHeart)
    C_FriendsSendHeart = 1009005,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_FriendsSearch)
    C_FriendsSearch = 1009006,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_FriendsApplyList)
    C_FriendsApplyList = 1009007,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_FriendsGroupCreate)
    C_FriendsGroupCreate = 1009010,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_FriendsGroupInvite)
    C_FriendsGroupInvite = 1009011,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_FriendsHandleInvite)
    C_FriendsHandleInvite = 1009012,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_FriendsGroupApply)
    C_FriendsGroupApply = 1009013,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_FriendsHandleGroupApply)
    C_FriendsHandleGroupApply = 1009014,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_FriendsGroupChangeMaster)
    C_FriendsGroupChangeMaster = 1009015,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_FriendsGroupTickOut)
    C_FriendsGroupTickOut = 1009016,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_FriendsGroupStopTalk)
    C_FriendsGroupStopTalk = 1009017,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_FriendsGroupApplyList)
    C_FriendsGroupApplyList = 1009018,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_FriendsGroupInviteList)
    C_FriendsGroupInviteList = 1009019,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_FriendsMyGroupList)
    C_FriendsMyGroupList = 1009020,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_FriendsMyGroupUserList)
    C_FriendsMyGroupUserList = 1009021,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_FriendsGroupSearch)
    C_FriendsGroupSearch = 10090022,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_FriendsApplyNotify)
    C_FriendsApplyNotify = 1009023,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_ChatInit)
    C_ChatInit = 1010000,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_SendChatMsg)
    C_SendChatMsg = 1010001,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_GetHistoryMsgList)
    C_GetHistoryMsgList = 1010002,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_ChatMessageNotify)
    C_ChatMessageNotify = 1010003,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_CrossChatOnline)
    C_CrossChatOnline = 1010004,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_CrossChatLogin)
    C_CrossChatLogin = 1010005,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_CrossChatGetRoomList)
    C_CrossChatGetRoomList = 1010006,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_CrossChatChangeRoom)
    C_CrossChatChangeRoom = 1010007,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_CrossChatNeedRelogin)
    C_CrossChatNeedRelogin = 1010008,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_ChatPrivateNotify)
    C_ChatPrivateNotify = 1010009,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_LoadMap)
    C_LoadMap = 1020001,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_BuyScene)
    C_BuyScene = 1020002,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_EditScene)
    C_EditScene = 1020003,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_ChooseScene)
    C_ChooseScene = 1020004,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_SceneDetail)
    C_SceneDetail = 1020005,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_SceneRenew)
    C_SceneRenew = 1020006,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_SceneChooseList)
    C_SceneChooseList = 1020007,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_LoadCollect)
    C_LoadCollect = 1020008,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_LoadCollect2)
    C_LoadCollect2 = 1020009,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_UseCollect)
    C_UseCollect = 1020010,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_UserScenePlan)
    C_UserScenePlan = 1020011,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_LoadCollectConfig)
    C_LoadCollectConfig = 1020012,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_CollectRecovery)
    C_CollectRecovery = 1020013,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_Placeontainer)
    C_Placeontainer = 1030001,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_LstMall)
    C_LstMall = 1030002,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_MerDetail)
    C_MerDetail = 1030003,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_CategoryList)
    C_CategoryList = 1030004,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_CategoryDetail)
    C_CategoryDetail = 1030005,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_ProductList)
    C_ProductList = 1030006,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_ProductDetail)
    C_ProductDetail = 1030007,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_CartList)
    C_CartList = 1030008,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_CartCreate)
    C_CartCreate = 1030009,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_CartChange)
    C_CartChange = 1030010,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_CartDelete)
    C_CartDelete = 1030011,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_RelationProductList)
    C_RelationProductList = 1030012,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_RelationCerate)
    C_RelationCerate = 1030013,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_RelationProductDel)
    C_RelationProductDel = 1030014,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_AddressList)
    C_AddressList = 1030015,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_AddressCreate)
    C_AddressCreate = 1030016,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_AddressDetail)
    C_AddressDetail = 1030017,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_AddressDefault)
    C_AddressDefault = 1030018,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_AddressDel)
    C_AddressDel = 1030019,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_ProductReply)
    C_ProductReply = 1030020,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_AddReply)
    C_AddReply = 1030021,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_MerchantShiYiList)
    C_MerchantShiYiList = 1030022,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_ProductSkuDetail)
    C_ProductSkuDetail = 1030023,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_UserOrderList)
    C_UserOrderList = 1030024,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_UserOrderDetail)
    C_UserOrderDetail = 1030025,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_UserOrderCreate)
    C_UserOrderCreate = 1030026,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_UserOrderCheck)
    C_UserOrderCheck = 1030027,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_UserOrderDel)
    C_UserOrderDel = 1030028,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_UserOrderPay)
    C_UserOrderPay = 1030029,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_UserOrderTake)
    C_UserOrderTake = 1030030,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_UserOrderExpress)
    C_UserOrderExpress = 1030031,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_Test)
    C_Test = 1030039,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_UserWalletRecharge)
    C_UserWalletRecharge = 1030040,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_RechargeResultNotify)
    C_RechargeResultNotify = 1031001,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_MultiRoomAction)
    C_MultiRoomAction = 1040001,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_CircleIssue)
    C_CircleIssue = 1050001,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_CircleList)
    C_CircleList = 1050002,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_CircleDelete)
    C_CircleDelete = 1050003,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_CircleComment)
    C_CircleComment = 1050004,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_CircleLike)
    C_CircleLike = 1050005,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_GetUserArticleNotes)
    C_GetUserArticleNotes = 1050006,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_GetCommentLists)
    C_GetCommentLists = 1050007,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_GetReplyLists)
    C_GetReplyLists = 1050008,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_RemoveUserArticleNotes)
    C_RemoveUserArticleNotes = 1050009,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_UserArticleLogNotify)
    C_UserArticleLogNotify = 1050010,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_ServerOnlyLogicStart)
    C_ServerOnlyLogicStart = 8000001,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_ServerOnlyRemoteLog)
    C_ServerOnlyRemoteLog = 8000002,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_ServerOnlyHeroCommentGetNewLikeList)
    C_ServerOnlyHeroCommentGetNewLikeList = 8000003,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_ServerOnlyMarkBattleDoNotDelete)
    C_ServerOnlyMarkBattleDoNotDelete = 8000004,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_ServerOnlySyncFullServerState)
    C_ServerOnlySyncFullServerState = 8100001,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_ServerOnlyServerStateNotify)
    C_ServerOnlyServerStateNotify = 8100002,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_ServerOnlyReportServerState)
    C_ServerOnlyReportServerState = 8100003,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_ServerOnlyCrossDataRetrieve)
    C_ServerOnlyCrossDataRetrieve = 8100011,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_ServerOnlyCrossDataUpdate)
    C_ServerOnlyCrossDataUpdate = 8100012,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_ServerOnlyCrossDataChangeSync)
    C_ServerOnlyCrossDataChangeSync = 8100013,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_ServerOnlyCrossSendUserNotify)
    C_ServerOnlyCrossSendUserNotify = 8100014,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_ServerOnlyCrossDumpHeroSnapshot)
    C_ServerOnlyCrossDumpHeroSnapshot = 8100015,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_ServerOnlyCrossDumpFormationAndHeroSnapshot)
    C_ServerOnlyCrossDumpFormationAndHeroSnapshot = 8100016,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_ServerOnlyCrossSendUserRsp)
    C_ServerOnlyCrossSendUserRsp = 8100017,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_ServerOnlyCrossRelayBattle)
    C_ServerOnlyCrossRelayBattle = 8100018,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_ServerOnlyCrossSyncBriefSnapshotPtl)
    C_ServerOnlyCrossSyncBriefSnapshotPtl = 8100019,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_ServerOnlyCrossStateReportPtl)
    C_ServerOnlyCrossStateReportPtl = 8100020,
    // @@protoc_insertion_point(enum_value:pbdef.CmdId.C_Person)
    C_Person = 8100021,
}

impl ::protobuf::Enum for CmdId {
    const NAME: &'static str = "CmdId";

    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<CmdId> {
        match value {
            0 => ::std::option::Option::Some(CmdId::C_None),
            1 => ::std::option::Option::Some(CmdId::C_GM),
            1000 => ::std::option::Option::Some(CmdId::C_Online),
            100101 => ::std::option::Option::Some(CmdId::C_UserDataChangeNotify),
            100103 => ::std::option::Option::Some(CmdId::C_PlayerLevelUpNotify),
            100104 => ::std::option::Option::Some(CmdId::C_OtherPlaceLoginKickoutNotify),
            100105 => ::std::option::Option::Some(CmdId::C_ServerWillShutdownNotify),
            100106 => ::std::option::Option::Some(CmdId::C_ActivityInfoChangeNotify),
            100107 => ::std::option::Option::Some(CmdId::C_UserActivityInfoChangeNotify),
            100108 => ::std::option::Option::Some(CmdId::C_BeKickOutNotify),
            100109 => ::std::option::Option::Some(CmdId::C_UserHeroImageUnlockNotify),
            100110 => ::std::option::Option::Some(CmdId::C_SystemMessageNotify),
            100111 => ::std::option::Option::Some(CmdId::C_SystemOfflineNotify),
            100112 => ::std::option::Option::Some(CmdId::C_ConnectionExpireNotify),
            100113 => ::std::option::Option::Some(CmdId::C_CommonStartNotify),
            1000001 => ::std::option::Option::Some(CmdId::C_Login),
            1000002 => ::std::option::Option::Some(CmdId::C_Re_Login),
            1009000 => ::std::option::Option::Some(CmdId::C_FriendsGet),
            1009001 => ::std::option::Option::Some(CmdId::C_FriendsApply),
            1009002 => ::std::option::Option::Some(CmdId::C_FriendsDel),
            1009003 => ::std::option::Option::Some(CmdId::C_FriendsApplyReply),
            1009004 => ::std::option::Option::Some(CmdId::C_FriendsMoveToBlackList),
            1009005 => ::std::option::Option::Some(CmdId::C_FriendsSendHeart),
            1009006 => ::std::option::Option::Some(CmdId::C_FriendsSearch),
            1009007 => ::std::option::Option::Some(CmdId::C_FriendsApplyList),
            1009010 => ::std::option::Option::Some(CmdId::C_FriendsGroupCreate),
            1009011 => ::std::option::Option::Some(CmdId::C_FriendsGroupInvite),
            1009012 => ::std::option::Option::Some(CmdId::C_FriendsHandleInvite),
            1009013 => ::std::option::Option::Some(CmdId::C_FriendsGroupApply),
            1009014 => ::std::option::Option::Some(CmdId::C_FriendsHandleGroupApply),
            1009015 => ::std::option::Option::Some(CmdId::C_FriendsGroupChangeMaster),
            1009016 => ::std::option::Option::Some(CmdId::C_FriendsGroupTickOut),
            1009017 => ::std::option::Option::Some(CmdId::C_FriendsGroupStopTalk),
            1009018 => ::std::option::Option::Some(CmdId::C_FriendsGroupApplyList),
            1009019 => ::std::option::Option::Some(CmdId::C_FriendsGroupInviteList),
            1009020 => ::std::option::Option::Some(CmdId::C_FriendsMyGroupList),
            1009021 => ::std::option::Option::Some(CmdId::C_FriendsMyGroupUserList),
            10090022 => ::std::option::Option::Some(CmdId::C_FriendsGroupSearch),
            1009023 => ::std::option::Option::Some(CmdId::C_FriendsApplyNotify),
            1010000 => ::std::option::Option::Some(CmdId::C_ChatInit),
            1010001 => ::std::option::Option::Some(CmdId::C_SendChatMsg),
            1010002 => ::std::option::Option::Some(CmdId::C_GetHistoryMsgList),
            1010003 => ::std::option::Option::Some(CmdId::C_ChatMessageNotify),
            1010004 => ::std::option::Option::Some(CmdId::C_CrossChatOnline),
            1010005 => ::std::option::Option::Some(CmdId::C_CrossChatLogin),
            1010006 => ::std::option::Option::Some(CmdId::C_CrossChatGetRoomList),
            1010007 => ::std::option::Option::Some(CmdId::C_CrossChatChangeRoom),
            1010008 => ::std::option::Option::Some(CmdId::C_CrossChatNeedRelogin),
            1010009 => ::std::option::Option::Some(CmdId::C_ChatPrivateNotify),
            1020001 => ::std::option::Option::Some(CmdId::C_LoadMap),
            1020002 => ::std::option::Option::Some(CmdId::C_BuyScene),
            1020003 => ::std::option::Option::Some(CmdId::C_EditScene),
            1020004 => ::std::option::Option::Some(CmdId::C_ChooseScene),
            1020005 => ::std::option::Option::Some(CmdId::C_SceneDetail),
            1020006 => ::std::option::Option::Some(CmdId::C_SceneRenew),
            1020007 => ::std::option::Option::Some(CmdId::C_SceneChooseList),
            1020008 => ::std::option::Option::Some(CmdId::C_LoadCollect),
            1020009 => ::std::option::Option::Some(CmdId::C_LoadCollect2),
            1020010 => ::std::option::Option::Some(CmdId::C_UseCollect),
            1020011 => ::std::option::Option::Some(CmdId::C_UserScenePlan),
            1020012 => ::std::option::Option::Some(CmdId::C_LoadCollectConfig),
            1020013 => ::std::option::Option::Some(CmdId::C_CollectRecovery),
            1030001 => ::std::option::Option::Some(CmdId::C_Placeontainer),
            1030002 => ::std::option::Option::Some(CmdId::C_LstMall),
            1030003 => ::std::option::Option::Some(CmdId::C_MerDetail),
            1030004 => ::std::option::Option::Some(CmdId::C_CategoryList),
            1030005 => ::std::option::Option::Some(CmdId::C_CategoryDetail),
            1030006 => ::std::option::Option::Some(CmdId::C_ProductList),
            1030007 => ::std::option::Option::Some(CmdId::C_ProductDetail),
            1030008 => ::std::option::Option::Some(CmdId::C_CartList),
            1030009 => ::std::option::Option::Some(CmdId::C_CartCreate),
            1030010 => ::std::option::Option::Some(CmdId::C_CartChange),
            1030011 => ::std::option::Option::Some(CmdId::C_CartDelete),
            1030012 => ::std::option::Option::Some(CmdId::C_RelationProductList),
            1030013 => ::std::option::Option::Some(CmdId::C_RelationCerate),
            1030014 => ::std::option::Option::Some(CmdId::C_RelationProductDel),
            1030015 => ::std::option::Option::Some(CmdId::C_AddressList),
            1030016 => ::std::option::Option::Some(CmdId::C_AddressCreate),
            1030017 => ::std::option::Option::Some(CmdId::C_AddressDetail),
            1030018 => ::std::option::Option::Some(CmdId::C_AddressDefault),
            1030019 => ::std::option::Option::Some(CmdId::C_AddressDel),
            1030020 => ::std::option::Option::Some(CmdId::C_ProductReply),
            1030021 => ::std::option::Option::Some(CmdId::C_AddReply),
            1030022 => ::std::option::Option::Some(CmdId::C_MerchantShiYiList),
            1030023 => ::std::option::Option::Some(CmdId::C_ProductSkuDetail),
            1030024 => ::std::option::Option::Some(CmdId::C_UserOrderList),
            1030025 => ::std::option::Option::Some(CmdId::C_UserOrderDetail),
            1030026 => ::std::option::Option::Some(CmdId::C_UserOrderCreate),
            1030027 => ::std::option::Option::Some(CmdId::C_UserOrderCheck),
            1030028 => ::std::option::Option::Some(CmdId::C_UserOrderDel),
            1030029 => ::std::option::Option::Some(CmdId::C_UserOrderPay),
            1030030 => ::std::option::Option::Some(CmdId::C_UserOrderTake),
            1030031 => ::std::option::Option::Some(CmdId::C_UserOrderExpress),
            1030039 => ::std::option::Option::Some(CmdId::C_Test),
            1030040 => ::std::option::Option::Some(CmdId::C_UserWalletRecharge),
            1031001 => ::std::option::Option::Some(CmdId::C_RechargeResultNotify),
            1040001 => ::std::option::Option::Some(CmdId::C_MultiRoomAction),
            1050001 => ::std::option::Option::Some(CmdId::C_CircleIssue),
            1050002 => ::std::option::Option::Some(CmdId::C_CircleList),
            1050003 => ::std::option::Option::Some(CmdId::C_CircleDelete),
            1050004 => ::std::option::Option::Some(CmdId::C_CircleComment),
            1050005 => ::std::option::Option::Some(CmdId::C_CircleLike),
            1050006 => ::std::option::Option::Some(CmdId::C_GetUserArticleNotes),
            1050007 => ::std::option::Option::Some(CmdId::C_GetCommentLists),
            1050008 => ::std::option::Option::Some(CmdId::C_GetReplyLists),
            1050009 => ::std::option::Option::Some(CmdId::C_RemoveUserArticleNotes),
            1050010 => ::std::option::Option::Some(CmdId::C_UserArticleLogNotify),
            8000001 => ::std::option::Option::Some(CmdId::C_ServerOnlyLogicStart),
            8000002 => ::std::option::Option::Some(CmdId::C_ServerOnlyRemoteLog),
            8000003 => ::std::option::Option::Some(CmdId::C_ServerOnlyHeroCommentGetNewLikeList),
            8000004 => ::std::option::Option::Some(CmdId::C_ServerOnlyMarkBattleDoNotDelete),
            8100001 => ::std::option::Option::Some(CmdId::C_ServerOnlySyncFullServerState),
            8100002 => ::std::option::Option::Some(CmdId::C_ServerOnlyServerStateNotify),
            8100003 => ::std::option::Option::Some(CmdId::C_ServerOnlyReportServerState),
            8100011 => ::std::option::Option::Some(CmdId::C_ServerOnlyCrossDataRetrieve),
            8100012 => ::std::option::Option::Some(CmdId::C_ServerOnlyCrossDataUpdate),
            8100013 => ::std::option::Option::Some(CmdId::C_ServerOnlyCrossDataChangeSync),
            8100014 => ::std::option::Option::Some(CmdId::C_ServerOnlyCrossSendUserNotify),
            8100015 => ::std::option::Option::Some(CmdId::C_ServerOnlyCrossDumpHeroSnapshot),
            8100016 => ::std::option::Option::Some(CmdId::C_ServerOnlyCrossDumpFormationAndHeroSnapshot),
            8100017 => ::std::option::Option::Some(CmdId::C_ServerOnlyCrossSendUserRsp),
            8100018 => ::std::option::Option::Some(CmdId::C_ServerOnlyCrossRelayBattle),
            8100019 => ::std::option::Option::Some(CmdId::C_ServerOnlyCrossSyncBriefSnapshotPtl),
            8100020 => ::std::option::Option::Some(CmdId::C_ServerOnlyCrossStateReportPtl),
            8100021 => ::std::option::Option::Some(CmdId::C_Person),
            _ => ::std::option::Option::None
        }
    }

    fn from_str(str: &str) -> ::std::option::Option<CmdId> {
        match str {
            "C_None" => ::std::option::Option::Some(CmdId::C_None),
            "C_GM" => ::std::option::Option::Some(CmdId::C_GM),
            "C_Online" => ::std::option::Option::Some(CmdId::C_Online),
            "C_UserDataChangeNotify" => ::std::option::Option::Some(CmdId::C_UserDataChangeNotify),
            "C_PlayerLevelUpNotify" => ::std::option::Option::Some(CmdId::C_PlayerLevelUpNotify),
            "C_OtherPlaceLoginKickoutNotify" => ::std::option::Option::Some(CmdId::C_OtherPlaceLoginKickoutNotify),
            "C_ServerWillShutdownNotify" => ::std::option::Option::Some(CmdId::C_ServerWillShutdownNotify),
            "C_ActivityInfoChangeNotify" => ::std::option::Option::Some(CmdId::C_ActivityInfoChangeNotify),
            "C_UserActivityInfoChangeNotify" => ::std::option::Option::Some(CmdId::C_UserActivityInfoChangeNotify),
            "C_BeKickOutNotify" => ::std::option::Option::Some(CmdId::C_BeKickOutNotify),
            "C_UserHeroImageUnlockNotify" => ::std::option::Option::Some(CmdId::C_UserHeroImageUnlockNotify),
            "C_SystemMessageNotify" => ::std::option::Option::Some(CmdId::C_SystemMessageNotify),
            "C_SystemOfflineNotify" => ::std::option::Option::Some(CmdId::C_SystemOfflineNotify),
            "C_ConnectionExpireNotify" => ::std::option::Option::Some(CmdId::C_ConnectionExpireNotify),
            "C_CommonStartNotify" => ::std::option::Option::Some(CmdId::C_CommonStartNotify),
            "C_Login" => ::std::option::Option::Some(CmdId::C_Login),
            "C_Re_Login" => ::std::option::Option::Some(CmdId::C_Re_Login),
            "C_FriendsGet" => ::std::option::Option::Some(CmdId::C_FriendsGet),
            "C_FriendsApply" => ::std::option::Option::Some(CmdId::C_FriendsApply),
            "C_FriendsDel" => ::std::option::Option::Some(CmdId::C_FriendsDel),
            "C_FriendsApplyReply" => ::std::option::Option::Some(CmdId::C_FriendsApplyReply),
            "C_FriendsMoveToBlackList" => ::std::option::Option::Some(CmdId::C_FriendsMoveToBlackList),
            "C_FriendsSendHeart" => ::std::option::Option::Some(CmdId::C_FriendsSendHeart),
            "C_FriendsSearch" => ::std::option::Option::Some(CmdId::C_FriendsSearch),
            "C_FriendsApplyList" => ::std::option::Option::Some(CmdId::C_FriendsApplyList),
            "C_FriendsGroupCreate" => ::std::option::Option::Some(CmdId::C_FriendsGroupCreate),
            "C_FriendsGroupInvite" => ::std::option::Option::Some(CmdId::C_FriendsGroupInvite),
            "C_FriendsHandleInvite" => ::std::option::Option::Some(CmdId::C_FriendsHandleInvite),
            "C_FriendsGroupApply" => ::std::option::Option::Some(CmdId::C_FriendsGroupApply),
            "C_FriendsHandleGroupApply" => ::std::option::Option::Some(CmdId::C_FriendsHandleGroupApply),
            "C_FriendsGroupChangeMaster" => ::std::option::Option::Some(CmdId::C_FriendsGroupChangeMaster),
            "C_FriendsGroupTickOut" => ::std::option::Option::Some(CmdId::C_FriendsGroupTickOut),
            "C_FriendsGroupStopTalk" => ::std::option::Option::Some(CmdId::C_FriendsGroupStopTalk),
            "C_FriendsGroupApplyList" => ::std::option::Option::Some(CmdId::C_FriendsGroupApplyList),
            "C_FriendsGroupInviteList" => ::std::option::Option::Some(CmdId::C_FriendsGroupInviteList),
            "C_FriendsMyGroupList" => ::std::option::Option::Some(CmdId::C_FriendsMyGroupList),
            "C_FriendsMyGroupUserList" => ::std::option::Option::Some(CmdId::C_FriendsMyGroupUserList),
            "C_FriendsGroupSearch" => ::std::option::Option::Some(CmdId::C_FriendsGroupSearch),
            "C_FriendsApplyNotify" => ::std::option::Option::Some(CmdId::C_FriendsApplyNotify),
            "C_ChatInit" => ::std::option::Option::Some(CmdId::C_ChatInit),
            "C_SendChatMsg" => ::std::option::Option::Some(CmdId::C_SendChatMsg),
            "C_GetHistoryMsgList" => ::std::option::Option::Some(CmdId::C_GetHistoryMsgList),
            "C_ChatMessageNotify" => ::std::option::Option::Some(CmdId::C_ChatMessageNotify),
            "C_CrossChatOnline" => ::std::option::Option::Some(CmdId::C_CrossChatOnline),
            "C_CrossChatLogin" => ::std::option::Option::Some(CmdId::C_CrossChatLogin),
            "C_CrossChatGetRoomList" => ::std::option::Option::Some(CmdId::C_CrossChatGetRoomList),
            "C_CrossChatChangeRoom" => ::std::option::Option::Some(CmdId::C_CrossChatChangeRoom),
            "C_CrossChatNeedRelogin" => ::std::option::Option::Some(CmdId::C_CrossChatNeedRelogin),
            "C_ChatPrivateNotify" => ::std::option::Option::Some(CmdId::C_ChatPrivateNotify),
            "C_LoadMap" => ::std::option::Option::Some(CmdId::C_LoadMap),
            "C_BuyScene" => ::std::option::Option::Some(CmdId::C_BuyScene),
            "C_EditScene" => ::std::option::Option::Some(CmdId::C_EditScene),
            "C_ChooseScene" => ::std::option::Option::Some(CmdId::C_ChooseScene),
            "C_SceneDetail" => ::std::option::Option::Some(CmdId::C_SceneDetail),
            "C_SceneRenew" => ::std::option::Option::Some(CmdId::C_SceneRenew),
            "C_SceneChooseList" => ::std::option::Option::Some(CmdId::C_SceneChooseList),
            "C_LoadCollect" => ::std::option::Option::Some(CmdId::C_LoadCollect),
            "C_LoadCollect2" => ::std::option::Option::Some(CmdId::C_LoadCollect2),
            "C_UseCollect" => ::std::option::Option::Some(CmdId::C_UseCollect),
            "C_UserScenePlan" => ::std::option::Option::Some(CmdId::C_UserScenePlan),
            "C_LoadCollectConfig" => ::std::option::Option::Some(CmdId::C_LoadCollectConfig),
            "C_CollectRecovery" => ::std::option::Option::Some(CmdId::C_CollectRecovery),
            "C_Placeontainer" => ::std::option::Option::Some(CmdId::C_Placeontainer),
            "C_LstMall" => ::std::option::Option::Some(CmdId::C_LstMall),
            "C_MerDetail" => ::std::option::Option::Some(CmdId::C_MerDetail),
            "C_CategoryList" => ::std::option::Option::Some(CmdId::C_CategoryList),
            "C_CategoryDetail" => ::std::option::Option::Some(CmdId::C_CategoryDetail),
            "C_ProductList" => ::std::option::Option::Some(CmdId::C_ProductList),
            "C_ProductDetail" => ::std::option::Option::Some(CmdId::C_ProductDetail),
            "C_CartList" => ::std::option::Option::Some(CmdId::C_CartList),
            "C_CartCreate" => ::std::option::Option::Some(CmdId::C_CartCreate),
            "C_CartChange" => ::std::option::Option::Some(CmdId::C_CartChange),
            "C_CartDelete" => ::std::option::Option::Some(CmdId::C_CartDelete),
            "C_RelationProductList" => ::std::option::Option::Some(CmdId::C_RelationProductList),
            "C_RelationCerate" => ::std::option::Option::Some(CmdId::C_RelationCerate),
            "C_RelationProductDel" => ::std::option::Option::Some(CmdId::C_RelationProductDel),
            "C_AddressList" => ::std::option::Option::Some(CmdId::C_AddressList),
            "C_AddressCreate" => ::std::option::Option::Some(CmdId::C_AddressCreate),
            "C_AddressDetail" => ::std::option::Option::Some(CmdId::C_AddressDetail),
            "C_AddressDefault" => ::std::option::Option::Some(CmdId::C_AddressDefault),
            "C_AddressDel" => ::std::option::Option::Some(CmdId::C_AddressDel),
            "C_ProductReply" => ::std::option::Option::Some(CmdId::C_ProductReply),
            "C_AddReply" => ::std::option::Option::Some(CmdId::C_AddReply),
            "C_MerchantShiYiList" => ::std::option::Option::Some(CmdId::C_MerchantShiYiList),
            "C_ProductSkuDetail" => ::std::option::Option::Some(CmdId::C_ProductSkuDetail),
            "C_UserOrderList" => ::std::option::Option::Some(CmdId::C_UserOrderList),
            "C_UserOrderDetail" => ::std::option::Option::Some(CmdId::C_UserOrderDetail),
            "C_UserOrderCreate" => ::std::option::Option::Some(CmdId::C_UserOrderCreate),
            "C_UserOrderCheck" => ::std::option::Option::Some(CmdId::C_UserOrderCheck),
            "C_UserOrderDel" => ::std::option::Option::Some(CmdId::C_UserOrderDel),
            "C_UserOrderPay" => ::std::option::Option::Some(CmdId::C_UserOrderPay),
            "C_UserOrderTake" => ::std::option::Option::Some(CmdId::C_UserOrderTake),
            "C_UserOrderExpress" => ::std::option::Option::Some(CmdId::C_UserOrderExpress),
            "C_Test" => ::std::option::Option::Some(CmdId::C_Test),
            "C_UserWalletRecharge" => ::std::option::Option::Some(CmdId::C_UserWalletRecharge),
            "C_RechargeResultNotify" => ::std::option::Option::Some(CmdId::C_RechargeResultNotify),
            "C_MultiRoomAction" => ::std::option::Option::Some(CmdId::C_MultiRoomAction),
            "C_CircleIssue" => ::std::option::Option::Some(CmdId::C_CircleIssue),
            "C_CircleList" => ::std::option::Option::Some(CmdId::C_CircleList),
            "C_CircleDelete" => ::std::option::Option::Some(CmdId::C_CircleDelete),
            "C_CircleComment" => ::std::option::Option::Some(CmdId::C_CircleComment),
            "C_CircleLike" => ::std::option::Option::Some(CmdId::C_CircleLike),
            "C_GetUserArticleNotes" => ::std::option::Option::Some(CmdId::C_GetUserArticleNotes),
            "C_GetCommentLists" => ::std::option::Option::Some(CmdId::C_GetCommentLists),
            "C_GetReplyLists" => ::std::option::Option::Some(CmdId::C_GetReplyLists),
            "C_RemoveUserArticleNotes" => ::std::option::Option::Some(CmdId::C_RemoveUserArticleNotes),
            "C_UserArticleLogNotify" => ::std::option::Option::Some(CmdId::C_UserArticleLogNotify),
            "C_ServerOnlyLogicStart" => ::std::option::Option::Some(CmdId::C_ServerOnlyLogicStart),
            "C_ServerOnlyRemoteLog" => ::std::option::Option::Some(CmdId::C_ServerOnlyRemoteLog),
            "C_ServerOnlyHeroCommentGetNewLikeList" => ::std::option::Option::Some(CmdId::C_ServerOnlyHeroCommentGetNewLikeList),
            "C_ServerOnlyMarkBattleDoNotDelete" => ::std::option::Option::Some(CmdId::C_ServerOnlyMarkBattleDoNotDelete),
            "C_ServerOnlySyncFullServerState" => ::std::option::Option::Some(CmdId::C_ServerOnlySyncFullServerState),
            "C_ServerOnlyServerStateNotify" => ::std::option::Option::Some(CmdId::C_ServerOnlyServerStateNotify),
            "C_ServerOnlyReportServerState" => ::std::option::Option::Some(CmdId::C_ServerOnlyReportServerState),
            "C_ServerOnlyCrossDataRetrieve" => ::std::option::Option::Some(CmdId::C_ServerOnlyCrossDataRetrieve),
            "C_ServerOnlyCrossDataUpdate" => ::std::option::Option::Some(CmdId::C_ServerOnlyCrossDataUpdate),
            "C_ServerOnlyCrossDataChangeSync" => ::std::option::Option::Some(CmdId::C_ServerOnlyCrossDataChangeSync),
            "C_ServerOnlyCrossSendUserNotify" => ::std::option::Option::Some(CmdId::C_ServerOnlyCrossSendUserNotify),
            "C_ServerOnlyCrossDumpHeroSnapshot" => ::std::option::Option::Some(CmdId::C_ServerOnlyCrossDumpHeroSnapshot),
            "C_ServerOnlyCrossDumpFormationAndHeroSnapshot" => ::std::option::Option::Some(CmdId::C_ServerOnlyCrossDumpFormationAndHeroSnapshot),
            "C_ServerOnlyCrossSendUserRsp" => ::std::option::Option::Some(CmdId::C_ServerOnlyCrossSendUserRsp),
            "C_ServerOnlyCrossRelayBattle" => ::std::option::Option::Some(CmdId::C_ServerOnlyCrossRelayBattle),
            "C_ServerOnlyCrossSyncBriefSnapshotPtl" => ::std::option::Option::Some(CmdId::C_ServerOnlyCrossSyncBriefSnapshotPtl),
            "C_ServerOnlyCrossStateReportPtl" => ::std::option::Option::Some(CmdId::C_ServerOnlyCrossStateReportPtl),
            "C_Person" => ::std::option::Option::Some(CmdId::C_Person),
            _ => ::std::option::Option::None
        }
    }

    const VALUES: &'static [CmdId] = &[
        CmdId::C_None,
        CmdId::C_GM,
        CmdId::C_Online,
        CmdId::C_UserDataChangeNotify,
        CmdId::C_PlayerLevelUpNotify,
        CmdId::C_OtherPlaceLoginKickoutNotify,
        CmdId::C_ServerWillShutdownNotify,
        CmdId::C_ActivityInfoChangeNotify,
        CmdId::C_UserActivityInfoChangeNotify,
        CmdId::C_BeKickOutNotify,
        CmdId::C_UserHeroImageUnlockNotify,
        CmdId::C_SystemMessageNotify,
        CmdId::C_SystemOfflineNotify,
        CmdId::C_ConnectionExpireNotify,
        CmdId::C_CommonStartNotify,
        CmdId::C_Login,
        CmdId::C_Re_Login,
        CmdId::C_FriendsGet,
        CmdId::C_FriendsApply,
        CmdId::C_FriendsDel,
        CmdId::C_FriendsApplyReply,
        CmdId::C_FriendsMoveToBlackList,
        CmdId::C_FriendsSendHeart,
        CmdId::C_FriendsSearch,
        CmdId::C_FriendsApplyList,
        CmdId::C_FriendsGroupCreate,
        CmdId::C_FriendsGroupInvite,
        CmdId::C_FriendsHandleInvite,
        CmdId::C_FriendsGroupApply,
        CmdId::C_FriendsHandleGroupApply,
        CmdId::C_FriendsGroupChangeMaster,
        CmdId::C_FriendsGroupTickOut,
        CmdId::C_FriendsGroupStopTalk,
        CmdId::C_FriendsGroupApplyList,
        CmdId::C_FriendsGroupInviteList,
        CmdId::C_FriendsMyGroupList,
        CmdId::C_FriendsMyGroupUserList,
        CmdId::C_FriendsGroupSearch,
        CmdId::C_FriendsApplyNotify,
        CmdId::C_ChatInit,
        CmdId::C_SendChatMsg,
        CmdId::C_GetHistoryMsgList,
        CmdId::C_ChatMessageNotify,
        CmdId::C_CrossChatOnline,
        CmdId::C_CrossChatLogin,
        CmdId::C_CrossChatGetRoomList,
        CmdId::C_CrossChatChangeRoom,
        CmdId::C_CrossChatNeedRelogin,
        CmdId::C_ChatPrivateNotify,
        CmdId::C_LoadMap,
        CmdId::C_BuyScene,
        CmdId::C_EditScene,
        CmdId::C_ChooseScene,
        CmdId::C_SceneDetail,
        CmdId::C_SceneRenew,
        CmdId::C_SceneChooseList,
        CmdId::C_LoadCollect,
        CmdId::C_LoadCollect2,
        CmdId::C_UseCollect,
        CmdId::C_UserScenePlan,
        CmdId::C_LoadCollectConfig,
        CmdId::C_CollectRecovery,
        CmdId::C_Placeontainer,
        CmdId::C_LstMall,
        CmdId::C_MerDetail,
        CmdId::C_CategoryList,
        CmdId::C_CategoryDetail,
        CmdId::C_ProductList,
        CmdId::C_ProductDetail,
        CmdId::C_CartList,
        CmdId::C_CartCreate,
        CmdId::C_CartChange,
        CmdId::C_CartDelete,
        CmdId::C_RelationProductList,
        CmdId::C_RelationCerate,
        CmdId::C_RelationProductDel,
        CmdId::C_AddressList,
        CmdId::C_AddressCreate,
        CmdId::C_AddressDetail,
        CmdId::C_AddressDefault,
        CmdId::C_AddressDel,
        CmdId::C_ProductReply,
        CmdId::C_AddReply,
        CmdId::C_MerchantShiYiList,
        CmdId::C_ProductSkuDetail,
        CmdId::C_UserOrderList,
        CmdId::C_UserOrderDetail,
        CmdId::C_UserOrderCreate,
        CmdId::C_UserOrderCheck,
        CmdId::C_UserOrderDel,
        CmdId::C_UserOrderPay,
        CmdId::C_UserOrderTake,
        CmdId::C_UserOrderExpress,
        CmdId::C_Test,
        CmdId::C_UserWalletRecharge,
        CmdId::C_RechargeResultNotify,
        CmdId::C_MultiRoomAction,
        CmdId::C_CircleIssue,
        CmdId::C_CircleList,
        CmdId::C_CircleDelete,
        CmdId::C_CircleComment,
        CmdId::C_CircleLike,
        CmdId::C_GetUserArticleNotes,
        CmdId::C_GetCommentLists,
        CmdId::C_GetReplyLists,
        CmdId::C_RemoveUserArticleNotes,
        CmdId::C_UserArticleLogNotify,
        CmdId::C_ServerOnlyLogicStart,
        CmdId::C_ServerOnlyRemoteLog,
        CmdId::C_ServerOnlyHeroCommentGetNewLikeList,
        CmdId::C_ServerOnlyMarkBattleDoNotDelete,
        CmdId::C_ServerOnlySyncFullServerState,
        CmdId::C_ServerOnlyServerStateNotify,
        CmdId::C_ServerOnlyReportServerState,
        CmdId::C_ServerOnlyCrossDataRetrieve,
        CmdId::C_ServerOnlyCrossDataUpdate,
        CmdId::C_ServerOnlyCrossDataChangeSync,
        CmdId::C_ServerOnlyCrossSendUserNotify,
        CmdId::C_ServerOnlyCrossDumpHeroSnapshot,
        CmdId::C_ServerOnlyCrossDumpFormationAndHeroSnapshot,
        CmdId::C_ServerOnlyCrossSendUserRsp,
        CmdId::C_ServerOnlyCrossRelayBattle,
        CmdId::C_ServerOnlyCrossSyncBriefSnapshotPtl,
        CmdId::C_ServerOnlyCrossStateReportPtl,
        CmdId::C_Person,
    ];
}

impl ::protobuf::EnumFull for CmdId {
    fn enum_descriptor() -> ::protobuf::reflect::EnumDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().enum_by_package_relative_name("CmdId").unwrap()).clone()
    }

    fn descriptor(&self) -> ::protobuf::reflect::EnumValueDescriptor {
        let index = match self {
            CmdId::C_None => 0,
            CmdId::C_GM => 1,
            CmdId::C_Online => 2,
            CmdId::C_UserDataChangeNotify => 3,
            CmdId::C_PlayerLevelUpNotify => 4,
            CmdId::C_OtherPlaceLoginKickoutNotify => 5,
            CmdId::C_ServerWillShutdownNotify => 6,
            CmdId::C_ActivityInfoChangeNotify => 7,
            CmdId::C_UserActivityInfoChangeNotify => 8,
            CmdId::C_BeKickOutNotify => 9,
            CmdId::C_UserHeroImageUnlockNotify => 10,
            CmdId::C_SystemMessageNotify => 11,
            CmdId::C_SystemOfflineNotify => 12,
            CmdId::C_ConnectionExpireNotify => 13,
            CmdId::C_CommonStartNotify => 14,
            CmdId::C_Login => 15,
            CmdId::C_Re_Login => 16,
            CmdId::C_FriendsGet => 17,
            CmdId::C_FriendsApply => 18,
            CmdId::C_FriendsDel => 19,
            CmdId::C_FriendsApplyReply => 20,
            CmdId::C_FriendsMoveToBlackList => 21,
            CmdId::C_FriendsSendHeart => 22,
            CmdId::C_FriendsSearch => 23,
            CmdId::C_FriendsApplyList => 24,
            CmdId::C_FriendsGroupCreate => 25,
            CmdId::C_FriendsGroupInvite => 26,
            CmdId::C_FriendsHandleInvite => 27,
            CmdId::C_FriendsGroupApply => 28,
            CmdId::C_FriendsHandleGroupApply => 29,
            CmdId::C_FriendsGroupChangeMaster => 30,
            CmdId::C_FriendsGroupTickOut => 31,
            CmdId::C_FriendsGroupStopTalk => 32,
            CmdId::C_FriendsGroupApplyList => 33,
            CmdId::C_FriendsGroupInviteList => 34,
            CmdId::C_FriendsMyGroupList => 35,
            CmdId::C_FriendsMyGroupUserList => 36,
            CmdId::C_FriendsGroupSearch => 37,
            CmdId::C_FriendsApplyNotify => 38,
            CmdId::C_ChatInit => 39,
            CmdId::C_SendChatMsg => 40,
            CmdId::C_GetHistoryMsgList => 41,
            CmdId::C_ChatMessageNotify => 42,
            CmdId::C_CrossChatOnline => 43,
            CmdId::C_CrossChatLogin => 44,
            CmdId::C_CrossChatGetRoomList => 45,
            CmdId::C_CrossChatChangeRoom => 46,
            CmdId::C_CrossChatNeedRelogin => 47,
            CmdId::C_ChatPrivateNotify => 48,
            CmdId::C_LoadMap => 49,
            CmdId::C_BuyScene => 50,
            CmdId::C_EditScene => 51,
            CmdId::C_ChooseScene => 52,
            CmdId::C_SceneDetail => 53,
            CmdId::C_SceneRenew => 54,
            CmdId::C_SceneChooseList => 55,
            CmdId::C_LoadCollect => 56,
            CmdId::C_LoadCollect2 => 57,
            CmdId::C_UseCollect => 58,
            CmdId::C_UserScenePlan => 59,
            CmdId::C_LoadCollectConfig => 60,
            CmdId::C_CollectRecovery => 61,
            CmdId::C_Placeontainer => 62,
            CmdId::C_LstMall => 63,
            CmdId::C_MerDetail => 64,
            CmdId::C_CategoryList => 65,
            CmdId::C_CategoryDetail => 66,
            CmdId::C_ProductList => 67,
            CmdId::C_ProductDetail => 68,
            CmdId::C_CartList => 69,
            CmdId::C_CartCreate => 70,
            CmdId::C_CartChange => 71,
            CmdId::C_CartDelete => 72,
            CmdId::C_RelationProductList => 73,
            CmdId::C_RelationCerate => 74,
            CmdId::C_RelationProductDel => 75,
            CmdId::C_AddressList => 76,
            CmdId::C_AddressCreate => 77,
            CmdId::C_AddressDetail => 78,
            CmdId::C_AddressDefault => 79,
            CmdId::C_AddressDel => 80,
            CmdId::C_ProductReply => 81,
            CmdId::C_AddReply => 82,
            CmdId::C_MerchantShiYiList => 83,
            CmdId::C_ProductSkuDetail => 84,
            CmdId::C_UserOrderList => 85,
            CmdId::C_UserOrderDetail => 86,
            CmdId::C_UserOrderCreate => 87,
            CmdId::C_UserOrderCheck => 88,
            CmdId::C_UserOrderDel => 89,
            CmdId::C_UserOrderPay => 90,
            CmdId::C_UserOrderTake => 91,
            CmdId::C_UserOrderExpress => 92,
            CmdId::C_Test => 93,
            CmdId::C_UserWalletRecharge => 94,
            CmdId::C_RechargeResultNotify => 95,
            CmdId::C_MultiRoomAction => 96,
            CmdId::C_CircleIssue => 97,
            CmdId::C_CircleList => 98,
            CmdId::C_CircleDelete => 99,
            CmdId::C_CircleComment => 100,
            CmdId::C_CircleLike => 101,
            CmdId::C_GetUserArticleNotes => 102,
            CmdId::C_GetCommentLists => 103,
            CmdId::C_GetReplyLists => 104,
            CmdId::C_RemoveUserArticleNotes => 105,
            CmdId::C_UserArticleLogNotify => 106,
            CmdId::C_ServerOnlyLogicStart => 107,
            CmdId::C_ServerOnlyRemoteLog => 108,
            CmdId::C_ServerOnlyHeroCommentGetNewLikeList => 109,
            CmdId::C_ServerOnlyMarkBattleDoNotDelete => 110,
            CmdId::C_ServerOnlySyncFullServerState => 111,
            CmdId::C_ServerOnlyServerStateNotify => 112,
            CmdId::C_ServerOnlyReportServerState => 113,
            CmdId::C_ServerOnlyCrossDataRetrieve => 114,
            CmdId::C_ServerOnlyCrossDataUpdate => 115,
            CmdId::C_ServerOnlyCrossDataChangeSync => 116,
            CmdId::C_ServerOnlyCrossSendUserNotify => 117,
            CmdId::C_ServerOnlyCrossDumpHeroSnapshot => 118,
            CmdId::C_ServerOnlyCrossDumpFormationAndHeroSnapshot => 119,
            CmdId::C_ServerOnlyCrossSendUserRsp => 120,
            CmdId::C_ServerOnlyCrossRelayBattle => 121,
            CmdId::C_ServerOnlyCrossSyncBriefSnapshotPtl => 122,
            CmdId::C_ServerOnlyCrossStateReportPtl => 123,
            CmdId::C_Person => 124,
        };
        Self::enum_descriptor().value_by_index(index)
    }
}

impl ::std::default::Default for CmdId {
    fn default() -> Self {
        CmdId::C_None
    }
}

impl CmdId {
    fn generated_enum_descriptor_data() -> ::protobuf::reflect::GeneratedEnumDescriptorData {
        ::protobuf::reflect::GeneratedEnumDescriptorData::new::<CmdId>("CmdId")
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x0bCmdId.proto\x12\x05pbdef*\x90\x1a\n\x05CmdId\x12\n\n\x06C_None\x10\
    \0\x12\x08\n\x04C_GM\x10\x01\x12\r\n\x08C_Online\x10\xe8\x07\x12\x1c\n\
    \x16C_UserDataChangeNotify\x10\x85\x8e\x06\x12\x1b\n\x15C_PlayerLevelUpN\
    otify\x10\x87\x8e\x06\x12$\n\x1eC_OtherPlaceLoginKickoutNotify\x10\x88\
    \x8e\x06\x12\x20\n\x1aC_ServerWillShutdownNotify\x10\x89\x8e\x06\x12\x20\
    \n\x1aC_ActivityInfoChangeNotify\x10\x8a\x8e\x06\x12$\n\x1eC_UserActivit\
    yInfoChangeNotify\x10\x8b\x8e\x06\x12\x17\n\x11C_BeKickOutNotify\x10\x8c\
    \x8e\x06\x12!\n\x1bC_UserHeroImageUnlockNotify\x10\x8d\x8e\x06\x12\x1b\n\
    \x15C_SystemMessageNotify\x10\x8e\x8e\x06\x12\x1b\n\x15C_SystemOfflineNo\
    tify\x10\x8f\x8e\x06\x12\x1e\n\x18C_ConnectionExpireNotify\x10\x90\x8e\
    \x06\x12\x19\n\x13C_CommonStartNotify\x10\x91\x8e\x06\x12\r\n\x07C_Login\
    \x10\xc1\x84=\x12\x10\n\nC_Re_Login\x10\xc2\x84=\x12\x12\n\x0cC_FriendsG\
    et\x10\xe8\xca=\x12\x14\n\x0eC_FriendsApply\x10\xe9\xca=\x12\x12\n\x0cC_\
    FriendsDel\x10\xea\xca=\x12\x19\n\x13C_FriendsApplyReply\x10\xeb\xca=\
    \x12\x1e\n\x18C_FriendsMoveToBlackList\x10\xec\xca=\x12\x18\n\x12C_Frien\
    dsSendHeart\x10\xed\xca=\x12\x15\n\x0fC_FriendsSearch\x10\xee\xca=\x12\
    \x18\n\x12C_FriendsApplyList\x10\xef\xca=\x12\x1a\n\x14C_FriendsGroupCre\
    ate\x10\xf2\xca=\x12\x1a\n\x14C_FriendsGroupInvite\x10\xf3\xca=\x12\x1b\
    \n\x15C_FriendsHandleInvite\x10\xf4\xca=\x12\x19\n\x13C_FriendsGroupAppl\
    y\x10\xf5\xca=\x12\x1f\n\x19C_FriendsHandleGroupApply\x10\xf6\xca=\x12\
    \x20\n\x1aC_FriendsGroupChangeMaster\x10\xf7\xca=\x12\x1b\n\x15C_Friends\
    GroupTickOut\x10\xf8\xca=\x12\x1c\n\x16C_FriendsGroupStopTalk\x10\xf9\
    \xca=\x12\x1d\n\x17C_FriendsGroupApplyList\x10\xfa\xca=\x12\x1e\n\x18C_F\
    riendsGroupInviteList\x10\xfb\xca=\x12\x1a\n\x14C_FriendsMyGroupList\x10\
    \xfc\xca=\x12\x1e\n\x18C_FriendsMyGroupUserList\x10\xfd\xca=\x12\x1b\n\
    \x14C_FriendsGroupSearch\x10\xa6\xec\xe7\x04\x12\x1a\n\x14C_FriendsApply\
    Notify\x10\xff\xca=\x12\x10\n\nC_ChatInit\x10\xd0\xd2=\x12\x13\n\rC_Send\
    ChatMsg\x10\xd1\xd2=\x12\x19\n\x13C_GetHistoryMsgList\x10\xd2\xd2=\x12\
    \x19\n\x13C_ChatMessageNotify\x10\xd3\xd2=\x12\x17\n\x11C_CrossChatOnlin\
    e\x10\xd4\xd2=\x12\x16\n\x10C_CrossChatLogin\x10\xd5\xd2=\x12\x1c\n\x16C\
    _CrossChatGetRoomList\x10\xd6\xd2=\x12\x1b\n\x15C_CrossChatChangeRoom\
    \x10\xd7\xd2=\x12\x1c\n\x16C_CrossChatNeedRelogin\x10\xd8\xd2=\x12\x19\n\
    \x13C_ChatPrivateNotify\x10\xd9\xd2=\x12\x0f\n\tC_LoadMap\x10\xe1\xa0>\
    \x12\x10\n\nC_BuyScene\x10\xe2\xa0>\x12\x11\n\x0bC_EditScene\x10\xe3\xa0\
    >\x12\x13\n\rC_ChooseScene\x10\xe4\xa0>\x12\x13\n\rC_SceneDetail\x10\xe5\
    \xa0>\x12\x12\n\x0cC_SceneRenew\x10\xe6\xa0>\x12\x17\n\x11C_SceneChooseL\
    ist\x10\xe7\xa0>\x12\x13\n\rC_LoadCollect\x10\xe8\xa0>\x12\x14\n\x0eC_Lo\
    adCollect2\x10\xe9\xa0>\x12\x12\n\x0cC_UseCollect\x10\xea\xa0>\x12\x15\n\
    \x0fC_UserScenePlan\x10\xeb\xa0>\x12\x19\n\x13C_LoadCollectConfig\x10\
    \xec\xa0>\x12\x17\n\x11C_CollectRecovery\x10\xed\xa0>\x12\x15\n\x0fC_Pla\
    ceontainer\x10\xf1\xee>\x12\x0f\n\tC_LstMall\x10\xf2\xee>\x12\x11\n\x0bC\
    _MerDetail\x10\xf3\xee>\x12\x14\n\x0eC_CategoryList\x10\xf4\xee>\x12\x16\
    \n\x10C_CategoryDetail\x10\xf5\xee>\x12\x13\n\rC_ProductList\x10\xf6\xee\
    >\x12\x15\n\x0fC_ProductDetail\x10\xf7\xee>\x12\x10\n\nC_CartList\x10\
    \xf8\xee>\x12\x12\n\x0cC_CartCreate\x10\xf9\xee>\x12\x12\n\x0cC_CartChan\
    ge\x10\xfa\xee>\x12\x12\n\x0cC_CartDelete\x10\xfb\xee>\x12\x1b\n\x15C_Re\
    lationProductList\x10\xfc\xee>\x12\x16\n\x10C_RelationCerate\x10\xfd\xee\
    >\x12\x1a\n\x14C_RelationProductDel\x10\xfe\xee>\x12\x13\n\rC_AddressLis\
    t\x10\xff\xee>\x12\x15\n\x0fC_AddressCreate\x10\x80\xef>\x12\x15\n\x0fC_\
    AddressDetail\x10\x81\xef>\x12\x16\n\x10C_AddressDefault\x10\x82\xef>\
    \x12\x12\n\x0cC_AddressDel\x10\x83\xef>\x12\x14\n\x0eC_ProductReply\x10\
    \x84\xef>\x12\x10\n\nC_AddReply\x10\x85\xef>\x12\x19\n\x13C_MerchantShiY\
    iList\x10\x86\xef>\x12\x18\n\x12C_ProductSkuDetail\x10\x87\xef>\x12\x15\
    \n\x0fC_UserOrderList\x10\x88\xef>\x12\x17\n\x11C_UserOrderDetail\x10\
    \x89\xef>\x12\x17\n\x11C_UserOrderCreate\x10\x8a\xef>\x12\x16\n\x10C_Use\
    rOrderCheck\x10\x8b\xef>\x12\x14\n\x0eC_UserOrderDel\x10\x8c\xef>\x12\
    \x14\n\x0eC_UserOrderPay\x10\x8d\xef>\x12\x15\n\x0fC_UserOrderTake\x10\
    \x8e\xef>\x12\x18\n\x12C_UserOrderExpress\x10\x8f\xef>\x12\x0c\n\x06C_Te\
    st\x10\x97\xef>\x12\x1a\n\x14C_UserWalletRecharge\x10\x98\xef>\x12\x1c\n\
    \x16C_RechargeResultNotify\x10\xd9\xf6>\x12\x17\n\x11C_MultiRoomAction\
    \x10\x81\xbd?\x12\x13\n\rC_CircleIssue\x10\x91\x8b@\x12\x12\n\x0cC_Circl\
    eList\x10\x92\x8b@\x12\x14\n\x0eC_CircleDelete\x10\x93\x8b@\x12\x15\n\
    \x0fC_CircleComment\x10\x94\x8b@\x12\x12\n\x0cC_CircleLike\x10\x95\x8b@\
    \x12\x1b\n\x15C_GetUserArticleNotes\x10\x96\x8b@\x12\x17\n\x11C_GetComme\
    ntLists\x10\x97\x8b@\x12\x15\n\x0fC_GetReplyLists\x10\x98\x8b@\x12\x1e\n\
    \x18C_RemoveUserArticleNotes\x10\x99\x8b@\x12\x1c\n\x16C_UserArticleLogN\
    otify\x10\x9a\x8b@\x12\x1d\n\x16C_ServerOnlyLogicStart\x10\x81\xa4\xe8\
    \x03\x12\x1c\n\x15C_ServerOnlyRemoteLog\x10\x82\xa4\xe8\x03\x12,\n%C_Ser\
    verOnlyHeroCommentGetNewLikeList\x10\x83\xa4\xe8\x03\x12(\n!C_ServerOnly\
    MarkBattleDoNotDelete\x10\x84\xa4\xe8\x03\x12&\n\x1fC_ServerOnlySyncFull\
    ServerState\x10\xa1\xb1\xee\x03\x12$\n\x1dC_ServerOnlyServerStateNotify\
    \x10\xa2\xb1\xee\x03\x12$\n\x1dC_ServerOnlyReportServerState\x10\xa3\xb1\
    \xee\x03\x12$\n\x1dC_ServerOnlyCrossDataRetrieve\x10\xab\xb1\xee\x03\x12\
    \"\n\x1bC_ServerOnlyCrossDataUpdate\x10\xac\xb1\xee\x03\x12&\n\x1fC_Serv\
    erOnlyCrossDataChangeSync\x10\xad\xb1\xee\x03\x12&\n\x1fC_ServerOnlyCros\
    sSendUserNotify\x10\xae\xb1\xee\x03\x12(\n!C_ServerOnlyCrossDumpHeroSnap\
    shot\x10\xaf\xb1\xee\x03\x124\n-C_ServerOnlyCrossDumpFormationAndHeroSna\
    pshot\x10\xb0\xb1\xee\x03\x12#\n\x1cC_ServerOnlyCrossSendUserRsp\x10\xb1\
    \xb1\xee\x03\x12#\n\x1cC_ServerOnlyCrossRelayBattle\x10\xb2\xb1\xee\x03\
    \x12,\n%C_ServerOnlyCrossSyncBriefSnapshotPtl\x10\xb3\xb1\xee\x03\x12&\n\
    \x1fC_ServerOnlyCrossStateReportPtl\x10\xb4\xb1\xee\x03\x12\x0f\n\x08C_P\
    erson\x10\xb5\xb1\xee\x03b\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(0);
            let mut enums = ::std::vec::Vec::with_capacity(1);
            enums.push(CmdId::generated_enum_descriptor_data());
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
