// This file is generated by rust-protobuf 3.3.0. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `TestData.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_3_0;

// @@protoc_insertion_point(message:pbdef.TestDataReq)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct TestDataReq {
    // message fields
    // @@protoc_insertion_point(field:pbdef.TestDataReq.x)
    pub x: ::std::string::String,
    // @@protoc_insertion_point(field:pbdef.TestDataReq.y)
    pub y: ::std::string::String,
    // @@protoc_insertion_point(field:pbdef.TestDataReq.z)
    pub z: ::std::string::String,
    // special fields
    // @@protoc_insertion_point(special_field:pbdef.TestDataReq.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a TestDataReq {
    fn default() -> &'a TestDataReq {
        <TestDataReq as ::protobuf::Message>::default_instance()
    }
}

impl TestDataReq {
    pub fn new() -> TestDataReq {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(3);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "x",
            |m: &TestDataReq| { &m.x },
            |m: &mut TestDataReq| { &mut m.x },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "y",
            |m: &TestDataReq| { &m.y },
            |m: &mut TestDataReq| { &mut m.y },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "z",
            |m: &TestDataReq| { &m.z },
            |m: &mut TestDataReq| { &mut m.z },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<TestDataReq>(
            "TestDataReq",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for TestDataReq {
    const NAME: &'static str = "TestDataReq";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.x = is.read_string()?;
                },
                18 => {
                    self.y = is.read_string()?;
                },
                26 => {
                    self.z = is.read_string()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.x.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.x);
        }
        if !self.y.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.y);
        }
        if !self.z.is_empty() {
            my_size += ::protobuf::rt::string_size(3, &self.z);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.x.is_empty() {
            os.write_string(1, &self.x)?;
        }
        if !self.y.is_empty() {
            os.write_string(2, &self.y)?;
        }
        if !self.z.is_empty() {
            os.write_string(3, &self.z)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> TestDataReq {
        TestDataReq::new()
    }

    fn clear(&mut self) {
        self.x.clear();
        self.y.clear();
        self.z.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static TestDataReq {
        static instance: TestDataReq = TestDataReq {
            x: ::std::string::String::new(),
            y: ::std::string::String::new(),
            z: ::std::string::String::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for TestDataReq {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("TestDataReq").unwrap()).clone()
    }
}

impl ::std::fmt::Display for TestDataReq {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for TestDataReq {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:pbdef.TestDataRsp)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct TestDataRsp {
    // message fields
    // @@protoc_insertion_point(field:pbdef.TestDataRsp.ret)
    pub ret: i32,
    // @@protoc_insertion_point(field:pbdef.TestDataRsp.msg)
    pub msg: ::std::string::String,
    // @@protoc_insertion_point(field:pbdef.TestDataRsp.data)
    pub data: i32,
    // special fields
    // @@protoc_insertion_point(special_field:pbdef.TestDataRsp.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a TestDataRsp {
    fn default() -> &'a TestDataRsp {
        <TestDataRsp as ::protobuf::Message>::default_instance()
    }
}

impl TestDataRsp {
    pub fn new() -> TestDataRsp {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(3);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "ret",
            |m: &TestDataRsp| { &m.ret },
            |m: &mut TestDataRsp| { &mut m.ret },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "msg",
            |m: &TestDataRsp| { &m.msg },
            |m: &mut TestDataRsp| { &mut m.msg },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "data",
            |m: &TestDataRsp| { &m.data },
            |m: &mut TestDataRsp| { &mut m.data },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<TestDataRsp>(
            "TestDataRsp",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for TestDataRsp {
    const NAME: &'static str = "TestDataRsp";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.ret = is.read_int32()?;
                },
                18 => {
                    self.msg = is.read_string()?;
                },
                24 => {
                    self.data = is.read_int32()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.ret != 0 {
            my_size += ::protobuf::rt::int32_size(1, self.ret);
        }
        if !self.msg.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.msg);
        }
        if self.data != 0 {
            my_size += ::protobuf::rt::int32_size(3, self.data);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.ret != 0 {
            os.write_int32(1, self.ret)?;
        }
        if !self.msg.is_empty() {
            os.write_string(2, &self.msg)?;
        }
        if self.data != 0 {
            os.write_int32(3, self.data)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> TestDataRsp {
        TestDataRsp::new()
    }

    fn clear(&mut self) {
        self.ret = 0;
        self.msg.clear();
        self.data = 0;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static TestDataRsp {
        static instance: TestDataRsp = TestDataRsp {
            ret: 0,
            msg: ::std::string::String::new(),
            data: 0,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for TestDataRsp {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("TestDataRsp").unwrap()).clone()
    }
}

impl ::std::fmt::Display for TestDataRsp {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for TestDataRsp {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x0eTestData.proto\x12\x05pbdef\"7\n\x0bTestDataReq\x12\x0c\n\x01x\x18\
    \x01\x20\x01(\tR\x01x\x12\x0c\n\x01y\x18\x02\x20\x01(\tR\x01y\x12\x0c\n\
    \x01z\x18\x03\x20\x01(\tR\x01z\"E\n\x0bTestDataRsp\x12\x10\n\x03ret\x18\
    \x01\x20\x01(\x05R\x03ret\x12\x10\n\x03msg\x18\x02\x20\x01(\tR\x03msg\
    \x12\x12\n\x04data\x18\x03\x20\x01(\x05R\x04datab\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(2);
            messages.push(TestDataReq::generated_message_descriptor_data());
            messages.push(TestDataRsp::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
