# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'config.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_region(object):
    def setupUi(self, region):
        region.setObjectName("region")
        region.resize(1456, 893)
        region.setStyleSheet("font: 25 12pt \"Microsoft YaHei\";")
        self.centralwidget = QtWidgets.QWidget(region)
        self.centralwidget.setObjectName("centralwidget")
        self.submit = QtWidgets.QPushButton(self.centralwidget)
        self.submit.setGeometry(QtCore.QRect(660, 220, 201, 71))
        self.submit.setObjectName("submit")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(70, 70, 525, 328))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.region_2 = QtWidgets.QLineEdit(self.widget)
        self.region_2.setObjectName("region_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.region_2)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.group = QtWidgets.QLineEdit(self.widget)
        self.group.setObjectName("group")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.group)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.latest = QtWidgets.QLineEdit(self.widget)
        self.latest.setObjectName("latest")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.latest)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.latestArea = QtWidgets.QLineEdit(self.widget)
        self.latestArea.setObjectName("latestArea")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.latestArea)
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.serverHost = QtWidgets.QLineEdit(self.widget)
        self.serverHost.setObjectName("serverHost")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.serverHost)
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.intraneHost = QtWidgets.QLineEdit(self.widget)
        self.intraneHost.setObjectName("intraneHost")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.intraneHost)
        self.label_13 = QtWidgets.QLabel(self.widget)
        self.label_13.setObjectName("label_13")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.gameStartTime = QtWidgets.QLineEdit(self.widget)
        self.gameStartTime.setObjectName("gameStartTime")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.gameStartTime)
        self.label_16 = QtWidgets.QLabel(self.widget)
        self.label_16.setObjectName("label_16")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.gsNum = QtWidgets.QLineEdit(self.widget)
        self.gsNum.setObjectName("gsNum")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.gsNum)
        self.label_17 = QtWidgets.QLabel(self.widget)
        self.label_17.setObjectName("label_17")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.gateNum = QtWidgets.QLineEdit(self.widget)
        self.gateNum.setObjectName("gateNum")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.gateNum)
        self.label_18 = QtWidgets.QLabel(self.widget)
        self.label_18.setObjectName("label_18")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.wsGateNum = QtWidgets.QLineEdit(self.widget)
        self.wsGateNum.setObjectName("wsGateNum")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.wsGateNum)
        self.horizontalLayout.addLayout(self.formLayout)
        self.splitter = QtWidgets.QSplitter(self.widget)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.widget1 = QtWidgets.QWidget(self.splitter)
        self.widget1.setObjectName("widget1")
        self.formLayout_3 = QtWidgets.QFormLayout(self.widget1)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_11 = QtWidgets.QLabel(self.widget1)
        self.label_11.setObjectName("label_11")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.logHost = QtWidgets.QLineEdit(self.widget1)
        self.logHost.setObjectName("logHost")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.logHost)
        self.label_12 = QtWidgets.QLabel(self.widget1)
        self.label_12.setObjectName("label_12")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.logPort = QtWidgets.QLineEdit(self.widget1)
        self.logPort.setObjectName("logPort")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.logPort)
        self.label_14 = QtWidgets.QLabel(self.widget1)
        self.label_14.setObjectName("label_14")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.logUser = QtWidgets.QLineEdit(self.widget1)
        self.logUser.setObjectName("logUser")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.logUser)
        self.label_15 = QtWidgets.QLabel(self.widget1)
        self.label_15.setObjectName("label_15")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.logPasswd = QtWidgets.QLineEdit(self.widget1)
        self.logPasswd.setObjectName("logPasswd")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.logPasswd)
        self.label_7 = QtWidgets.QLabel(self.widget1)
        self.label_7.setObjectName("label_7")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.dataHost = QtWidgets.QLineEdit(self.widget1)
        self.dataHost.setObjectName("dataHost")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.dataHost)
        self.label_8 = QtWidgets.QLabel(self.widget1)
        self.label_8.setObjectName("label_8")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.dataPort = QtWidgets.QLineEdit(self.widget1)
        self.dataPort.setObjectName("dataPort")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.dataPort)
        self.label_9 = QtWidgets.QLabel(self.widget1)
        self.label_9.setObjectName("label_9")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.dataUser = QtWidgets.QLineEdit(self.widget1)
        self.dataUser.setObjectName("dataUser")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.dataUser)
        self.label_10 = QtWidgets.QLabel(self.widget1)
        self.label_10.setObjectName("label_10")
        self.formLayout_3.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.dataPasswd = QtWidgets.QLineEdit(self.widget1)
        self.dataPasswd.setObjectName("dataPasswd")
        self.formLayout_3.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.dataPasswd)
        self.horizontalLayout.addWidget(self.splitter)
        region.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(region)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1456, 27))
        self.menubar.setObjectName("menubar")
        region.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(region)
        self.statusbar.setObjectName("statusbar")
        region.setStatusBar(self.statusbar)

        self.retranslateUi(region)
        QtCore.QMetaObject.connectSlotsByName(region)

    def retranslateUi(self, region):
        _translate = QtCore.QCoreApplication.translate
        region.setWindowTitle(_translate("region", "MainWindow"))
        self.submit.setText(_translate("region", "sbumit"))
        self.label.setText(_translate("region", "gameRegion"))
        self.region_2.setText(_translate("region", "1"))
        self.label_2.setText(_translate("region", "gameGroup"))
        self.group.setText(_translate("region", "1"))
        self.label_3.setText(_translate("region", "Latest"))
        self.latest.setText(_translate("region", "0"))
        self.label_4.setText(_translate("region", "LatestArea"))
        self.label_5.setText(_translate("region", "serverHost"))
        self.serverHost.setText(_translate("region", "0.0.0.0"))
        self.label_6.setText(_translate("region", "intranetHost"))
        self.intraneHost.setText(_translate("region", "127.0.0.1"))
        self.label_13.setText(_translate("region", "GameStartTime"))
        self.gameStartTime.setText(_translate("region", "2021-01-26"))
        self.label_16.setText(_translate("region", "GsNum"))
        self.gsNum.setText(_translate("region", "1"))
        self.label_17.setText(_translate("region", "GateNum"))
        self.gateNum.setText(_translate("region", "1"))
        self.label_18.setText(_translate("region", "WsGateNum"))
        self.wsGateNum.setText(_translate("region", "1"))
        self.label_11.setText(_translate("region", "logHost"))
        self.logHost.setText(_translate("region", "192.168.1.133"))
        self.label_12.setText(_translate("region", "logPort"))
        self.logPort.setText(_translate("region", "3308"))
        self.label_14.setText(_translate("region", "logUser"))
        self.logUser.setText(_translate("region", "root"))
        self.label_15.setText(_translate("region", "logPasswd"))
        self.logPasswd.setText(_translate("region", "123456"))
        self.label_7.setText(_translate("region", "dataHost"))
        self.dataHost.setText(_translate("region", "192.168.1.133"))
        self.label_8.setText(_translate("region", "dataPort"))
        self.dataPort.setText(_translate("region", "3308"))
        self.label_9.setText(_translate("region", "dataUser"))
        self.dataUser.setText(_translate("region", "root"))
        self.label_10.setText(_translate("region", "dataPasswd"))
        self.dataPasswd.setText(_translate("region", "123456"))

