all _all:
	go build -ldflags="-w -s" -o jjson
	#go build -o djson

exec _exec:
	./jjson -f ./data_juhe.json

# run
# jjson -f data_juhe.json
# jjson -d ./tmp
# jjson -d /home/lzj/norse/example/cmd/jjson/tmp
